"use client";
import "./globals.scss";
import Script from "next/script";
import type { Metadata } from "next";
import React from "react";
import Navbar from "./components/Layout_components/Navbar";
import { useBodyClass } from "./components/Layout_components/routesDriver";
import Head from "next/head";
import Wsp from "./components/Layout_components/Wsp";
import Bot from "./components/Layout_components/Bot";
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClass = useBodyClass();
  return (
    <html lang="en">
      <body className={bodyClass}>
        <main>{children}</main>
        <header>
          <Navbar />
        </header>

        <Bot />
        <Wsp />
        <Script
          type="module"
          src="/scripts/script_chatBot.js"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}
